### ISSUE TITLE
Rename github repo to `Elm Language Support`

### ISSUE THREAD

**Issue by stoivo** [elm-community/SublimeElmLanguageSupport#35]

**Comment by sentience** [comment]
@stoivo Good idea. This will require publishing a package move to Package Control.

**Comment by stoivo** [comment]
I can do that, should not be much work.

**Comment by stoivo** [comment]
We should name it ElmLanguageSupport since we can not have spaces in repo path

**Comment by sentience** [comment]
@stoivo I'm waiting for wbond/package_control_channel#6711 to merge so that stragglers on ST2 will only receive the older, compatible versions of this package. I'd rather not confuse things with two changes to our package pending at once. Once that merges, we should be good to go.

**Comment by sentience** [comment]
@stoivo Looks like GitHub auto-redirects the old repo name to the new, so we can make this change any time we want and update Package Control later.

I'm thinking the repo should be named SublimeElmLanguageSupport, to distinguish it from other editor integrations. This is the standard naming convention for Sublime packages.

**Comment by stoivo** [comment]
Yepp, let's wait for the first PR to get merged.
Adding Sublime to the name is a good idea. We should add a comment the readme, 
Manually installation:
```
git clone https://github.com/elm-community/Elm.tmLanguage.git 'Elm Language Support'
```
so it is easier to get first time contributors :)

**Comment by stoivo** [comment]
Should we proceed with the rename?
Open the PR to package_control_channel. When it actually is merged, change the name?

**Comment by stoivo** [comment]
I open a PR to change the name, https://github.com/wbond/package_control_channel/pull/6756

**Comment by sentience** [comment]
@stoivo Thanks for being so proactive, but in this case I believe we need to rename the repository first (GitHub will redirect the old URL), and _then_ update Package Control with the new URL.

I'm getting the ball rolling on renaming this repository now.

**Comment by sentience** [comment]
Request opened to rename this repository: elm-community/Manifesto#84

**Comment by sentience** [comment]
The repository has now been renamed! 👍

**Comment by stoivo** [comment]
Great
