### ISSUE TITLE
Elm 0.19 version flashes console window on Windows

### ISSUE THREAD

**Issue by ianmackenzie** [elm-community/SublimeElmLanguageSupport#50]
On Windows 10, every time I use Ctrl-B to build an Elm file I get a Windows console window that flashes over Sublime Text - certainly not a blocker, but a bit annoying!

**Comment by sentience** [comment]
Ooh, I wonder what could be causing this! I assume you've used the package with 0.18 previously and not had this problem?

**Comment by ianmackenzie** [comment]
I have! Elm 0.18 does not have the issue. It occurs to me that it could very well be an issue with the elm.exe executable itself - I can try to do some testing there.

**Comment by sentience** [comment]
@ianmackenzie Any luck diagnosing this further? This is the only known issue with the current beta, and I'm going to have to set up a Windows virtual machine to troubleshoot it.

**Comment by ianmackenzie** [comment]
I confess I haven't looked at it -  thanks for the reminder! I'm in the middle of a move right now but should be able to take a look later this week or this weekend.
