### ISSUE TITLE
Typo in 0.22.4 release notes

### ISSUE THREAD

**Issue by ianmackenzie** [elm-community/SublimeElmLanguageSupport#52]
In the 0.22.4 release notes there is a minor typo that nonetheless prevents proper updating to the prerelease version; 'Elm Language support' should be 'Elm Language Support' in

```
{
  "install_prereleases":
  [
    "Elm Language support"
  ],
}
```

**Comment by sentience** [comment]
Fixed by dfbb8bdc9a8403092c884d3eb893a270538cfa72
