### ISSUE TITLE
Disable elm-oracle

### ISSUE THREAD

**Issue by Bernardoow** [elm-community/SublimeElmLanguageSupport#61]
I want a settings to disable elm-oracle or elm-format.

**Comment by sentience** [comment]
elm-oracle support has been removed from the current beta version of this package, which supports Elm 0.19. Are you planning to or have you already upgraded to Elm 0.19? If so, I recommend upgrading to the beta version of this package.

As for elm-format, you can set the `"elm_format_on_save"` setting to `false` and it will disable the automatic invocation of elm-format when you save a file.

Will that work okay?

**Comment by Bernardoow** [comment]
I'm using the elm 0.19. 

I don't know what is happening because my elm-format not works more and sublime console.logs is saying about number of arguments in elm-oracle.

Ps. A three days ago it was working =/.
